"""Initial migration

Revision ID: e5ca50f1c3ab
Revises: 
Create Date: 2024-03-14 10:51:36.669819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5ca50f1c3ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monsters',
    sa.Column('monster_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('monster_id')
    )
    op.create_table('shop_items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('trainers',
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('trainer_id')
    )
    op.create_table('battles',
    sa.Column('battle_id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=True),
    sa.Column('monster_id', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters.monster_id'], name=op.f('fk_battles_monster_id_monsters')),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.trainer_id'], name=op.f('fk_battles_trainer_id_trainers')),
    sa.PrimaryKeyConstraint('battle_id')
    )
    op.create_table('trainer_items',
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['shop_items.item_id'], name=op.f('fk_trainer_items_item_id_shop_items')),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.trainer_id'], name=op.f('fk_trainer_items_trainer_id_trainers')),
    sa.PrimaryKeyConstraint('trainer_id', 'item_id')
    )
    op.create_table('trainer_monsters',
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('monster_id', sa.Integer(), nullable=False),
    sa.Column('capture_date', sa.Date(), nullable=True),
    sa.Column('level_when_caught', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters.monster_id'], name=op.f('fk_trainer_monsters_monster_id_monsters')),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.trainer_id'], name=op.f('fk_trainer_monsters_trainer_id_trainers')),
    sa.PrimaryKeyConstraint('trainer_id', 'monster_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trainer_monsters')
    op.drop_table('trainer_items')
    op.drop_table('battles')
    op.drop_table('trainers')
    op.drop_table('shop_items')
    op.drop_table('monsters')
    # ### end Alembic commands ###
